# Generated by Django 3.1.5 on 2021-01-09 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('suptitle', models.TextField(default=models.CharField(max_length=200, unique=True))),
                ('storys', models.FileField(upload_to='stores/')),
                ('Thumbnail', models.ImageField(upload_to='Thumbnail/')),
                ('posting_date', models.DateTimeField(auto_now=True)),
                ('is_listened', models.BooleanField(default=False)),
                ('is_liked', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
                ('listened', models.IntegerField(default=0)),
                ('language', models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('ZH', 'Chines'), ('NL', 'Dutch'), ('FR', 'French'), ('DE', 'German'), ('RU', 'Russian'), ('JA', 'Japanese')], max_length=3)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='story_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_of_comment', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.stores')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='story_channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250, unique=True)),
                ('subscribers', models.IntegerField(default=False)),
                ('creation_date', models.DateField(auto_now=True)),
                ('podcast_num', models.IntegerField(default=0)),
                ('storer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stores',
            name='channels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.story_channels'),
        ),
        migrations.AddField(
            model_name='stores',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.story_comments'),
        ),
        migrations.AddField(
            model_name='stores',
            name='podcasted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
