# Generated by Django 3.1.5 on 2021-01-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20210110_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='Thumbnail',
            field=models.ImageField(upload_to='stores_Thumbnail/'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='storys',
            field=models.FileField(upload_to='stores_audio/'),
        ),
    ]
