# Generated by Django 3.1.5 on 2021-01-14 12:13

import CODE_FOR_APPS.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20210110_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='story_comments',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stores',
            name='Thumbnail',
            field=models.ImageField(upload_to='stores_Thumbnail/', validators=[CODE_FOR_APPS.validators.validate_thumbnail_extension]),
        ),
        migrations.AlterField(
            model_name='stores',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stores',
            name='listened',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stores',
            name='storys',
            field=models.FileField(upload_to='stores_audio/', validators=[CODE_FOR_APPS.validators.validate_podcast_extension]),
        ),
        migrations.AlterField(
            model_name='story_channels',
            name='podcast_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story_channels',
            name='subscribers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
