# Generated by Django 3.1.5 on 2021-02-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20210114_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='is_locked',
            new_name='is_private_story',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='storys',
            new_name='stores',
        ),
        migrations.RenameField(
            model_name='story_channels',
            old_name='storer',
            new_name='storyteller',
        ),
        migrations.AddField(
            model_name='stores',
            name='is_stores_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story_comments',
            name='is_story_comment_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
