# Generated by Django 4.0.1 on 2022-07-09 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores_info',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comments.comment'),
        ),
        migrations.AlterField(
            model_name='stores_info',
            name='suptitle',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='story_comments',
        ),
    ]
