# Generated by Django 4.0.1 on 2022-07-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0002_alter_podcast_info_description_delete_comment'),
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='podcast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Podcast.podcast_info'),
            preserve_default=False,
        ),
    ]
