# Generated by Django 3.1.3 on 2020-12-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, default='No Description')),
                ('podcast', models.FileField(upload_to='podcasts/')),
                ('podcasted_by', models.CharField(max_length=100)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
    ]
