# Generated by Django 3.1.3 on 2020-12-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast_info',
            name='Thumbnail',
            field=models.ImageField(default='/home/ghassanmohder/Pictures/Glacier-Mountain.jpg', upload_to='Thumbnail/'),
            preserve_default=False,
        ),
    ]
