# Generated by Django 3.1.5 on 2021-02-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_podcast_channel_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_podcast_comment_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast_info',
            name='is_podcast_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast_info',
            name='is_private_podcast',
            field=models.BooleanField(default=False),
        ),
    ]
