# Generated by Django 3.1.3 on 2020-12-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0002_podcast_info_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast_info',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='podcast_info',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
