# Generated by Django 3.1.5 on 2021-02-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0002_auto_20210207_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast_info',
            name='Thumbnail',
            field=models.ImageField(upload_to='Thumbnail/'),
        ),
        migrations.AlterField(
            model_name='podcast_info',
            name='podcast',
            field=models.FileField(upload_to='podcasts/'),
        ),
    ]
