# Generated by Django 3.1.5 on 2021-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0003_auto_20210208_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast_info',
            name='Thumbnail',
            field=models.ImageField(upload_to='media/Thumbnail/'),
        ),
        migrations.AlterField(
            model_name='podcast_info',
            name='podcast',
            field=models.FileField(upload_to='media/podcasts/'),
        ),
    ]
