# Generated by Django 3.1.3 on 2020-12-25 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Podcast', '0003_auto_20201216_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast_info',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('ZH', 'Chines'), ('NL', 'Dutch'), ('FR', 'French'), ('DE', 'German'), ('RU', 'Russian'), ('JA', 'Japanese')], default='eng', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast_info',
            name='Title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='podcast_info',
            name='podcasted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_of_comment', models.DateTimeField(auto_now=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Podcast.podcast_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250, unique=True)),
                ('subscribers', models.IntegerField(default=False)),
                ('creation_date', models.DateField(auto_now=True)),
                ('podcast_num', models.IntegerField(default=0)),
                ('podcast_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='podcast_info',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Podcast.channel'),
            preserve_default=False,
        ),
    ]
