# Generated by Django 3.1.5 on 2021-03-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0004_auto_20210303_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast_info',
            name='Thumbnail',
            field=models.ImageField(upload_to='Thumbnail/'),
        ),
        migrations.AlterField(
            model_name='podcast_info',
            name='podcast',
            field=models.FileField(upload_to='podcasts/'),
        ),
    ]
