# Generated by Django 3.1.3 on 2020-12-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0004_auto_20201225_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast_info',
            name='posting_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
