# Generated by Django 4.0.1 on 2022-07-16 21:37

import Scripts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='podcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200, unique=True)),
                ('Description', models.TextField()),
                ('podcast', models.FileField(upload_to='podcasts/', validators=[Scripts.validators.validate_podcast_extension])),
                ('Thumbnail', models.ImageField(upload_to='Thumbnail/', validators=[Scripts.validators.validate_thumbnail_extension])),
                ('posting_date', models.DateTimeField(auto_now=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_liked', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('ZH', 'Chines'), ('NL', 'Dutch'), ('FR', 'French'), ('DE', 'German'), ('RU', 'Russian'), ('JA', 'Japanese')], max_length=3)),
                ('is_podcast_blocked', models.BooleanField(default=False)),
                ('is_private_podcast', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Channels.channel')),
                ('podcasted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
