# Generated by Django 4.0.1 on 2022-07-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast_info',
            name='Description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
